[package]
name = "rebar-example-server"
version = "0.1.0"
authors = ["DavidOConnor <david.alan.oconnor@gmail.com>"]
edition = "2018"

[dependencies]
rocket = "^0.4.0-rc.1"
serde = "^1.0.80"
serde_derive = "^1.0.80"
serde_json = "1.0.33"